export default {
  name: "黄磊",
  tel: 123454,
  totalCap: "一二三",
  zhi: "1",
  ge: 1,
  totalWeight: 100,
  totalPrice: 1100,
  table: [
    {
      profileCode: "1",
      profileName: "王小可",
      color: "男",
      changeQuantity: "120",
      price: "120",
      totalPrice: "120",
      materialType: "120",
      weight: "9089元",
    },
    {
      profileCode: "1",
      profileName: "王小可",
      color: "男",
      changeQuantity: "120",
      price: "120",
      totalPrice: "120",
      materialType: "120",
      weight: "9089元",
    },
    {
      profileCode: "1",
      profileName: "王小可",
      color: "男",
      changeQuantity: "120",
      price: "120",
      totalPrice: "120",
      materialType: "120",
      weight: "9089元",
    },
    {
      profileCode: "1",
      profileName: "王小可",
      color: "男",
      changeQuantity: "120",
      price: "120",
      totalPrice: "120",
      materialType: "120",
      weight: "9089元",
    },
    {
      profileCode: "1",
      profileName: "王小可",
      color: "男",
      changeQuantity: "120",
      price: "120",
      totalPrice: "120",
      materialType: "120",
      weight: "9089元",
    },
    {
      profileCode: "1",
      profileName: "王小可",
      color: "男",
      changeQuantity: "120",
      price: "120",
      totalPrice: "120",
      materialType: "120",
      weight: "9089元",
    },
  ],
};
