export default {
  panels: [
    {
      index: 0,
      name: 1,
      height: 287,
      width: 210,
      paperHeader: 52.5,
      paperFooter: 867.5,
      printElements: [
        {
          options: {
            left: 175.5,
            top: 10.5,
            height: 27,
            width: 259,
            title: "销售结算单",
            fontSize: 19,
            fontWeight: "600",
            textAlign: "center",
            lineHeight: 26,
            coordinateSync: true,
            widthHeightSync: true,
            draggable: false,
            qrCodeLevel: 0,
          },
          printElementType: { title: "自定义文本", type: "text" },
        },
        {
          options: {
            left: 50,
            top: 7.5,
            height: 42,
            width: 78,
            src: "../printLogo.png",
            fit: "contain",
            right: 117.49687957763672,
            bottom: 42.49687957763672,
            vCenter: 84.49687957763672,
            hCenter: 24.49687957763672,
          },
          printElementType: { title: "图片", type: "image" },
        },
        {
          options: {
            left: 191.75,
            top: 68.5,
            height: 21,
            width: 232.5,
            title: "制单日期",
            field: "makeDate",
            testData: "2023年5月30日",
            coordinateSync: false,
            widthHeightSync: false,
            fontSize: 12,
            qrCodeLevel: 0,
            right: 387,
            bottom: 98.25,
            vCenter: 270.75,
            hCenter: 87.75,
          },
          printElementType: { title: "这是更新后的元素", type: "text" },
        },
        {
          options: {
            left: 411.75,
            top: 68.5,
            height: 9.75,
            width: 169.5,
            title: "单号",
            field: "orderNum",
            testData: "GR230530001",
            coordinateSync: false,
            widthHeightSync: false,
            fontSize: 12,
            qrCodeLevel: 0,
            right: 546.75,
            bottom: 89.25,
            vCenter: 462,
            hCenter: 84.375,
          },
          printElementType: { title: "这是更新后的元素", type: "text" },
        },
        {
          options: {
            left: 181.25,
            top: 84.5,
            height: 16,
            width: 120,
            field: "tel",
            testData: "18888888888",
            fontSize: 6.75,
            fontWeight: "700",
            textContentVerticalAlign: "middle",
            title: "电话",
            coordinateSync: false,
            widthHeightSync: false,
            qrCodeLevel: 0,
          },
          printElementType: { title: "客户电话", type: "text" },
        },
        {
          options: {
            left: 59.75,
            top: 84.5,
            height: 16,
            width: 120,
            field: "name",
            testData: "高级客户",
            fontSize: 6.75,
            fontWeight: "700",
            textContentVerticalAlign: "middle",
            title: "客户",
            coordinateSync: false,
            widthHeightSync: false,
            qrCodeLevel: 0,
            right: 177,
            bottom: 197.4999885559082,
            vCenter: 117,
            hCenter: 189.4999885559082,
          },
          printElementType: { title: "客户名称", type: "text" },
        },
        {
          options: {
            left: 464.75,
            top: 84.5,
            height: 16,
            width: 120,
            field: "writeDate",
            testData: "2020-01-01",
            fontSize: 6.75,
            fontWeight: "700",
            textContentVerticalAlign: "middle",
            title: "录单日期",
            coordinateSync: false,
            widthHeightSync: false,
            qrCodeLevel: 0,
          },
          printElementType: { title: "业务日期", type: "text" },
        },
        {
          options: {
            left: 21.25,
            top: 100,
            height: 93,
            width: 568.5,
            field: "table",
            tableBorder: "border",
            tableHeaderBorder: "topBorder",
            tableHeaderCellBorder: "border",
            tableBodyRowBorder: "topBorder",
            tableFooterBorder: "topBorder",
            fields: [
              { text: "型材编码", field: "profileCode" },
              { text: "名称", field: "profileName" },
              { text: "颜色", field: "color" },
              { text: "数量", field: "changeQuantity" },
              { text: "重量", field: "weight" },
              { text: "单价", field: "price" },
              { text: "金额", field: "totalPrice" },
              { text: "单位", field: "materialType" },
            ],
            right: 596.25,
            bottom: 240.49635314941406,
            vCenter: 312,
            hCenter: 193.99635314941406,
            coordinateSync: false,
            widthHeightSync: false,
            footerFormatter:
              'function(t,e,n,i){return n ? `<tr><td style="padding:0 10px">其他费用：</td><td style="padding:0 10px" colspan="100">${n["otherCost"]}</td></tr><tr><td style="padding:0 10px">合计：</td><td style="padding:0 10px" colspan="1">重量：${n["totalWeight"]}</td><td style="padding:0 10px">支数：${n.zhi}</td><td style="padding:0 10px">件数：${n["ge"]}</td><td style="padding:0 10px" colspan="1">金额：${n["totalPrice"]}</td></tr><tr><td style="padding:0 10px">合计(大写)</td><td style="padding:0 10px" colspan="100">${n["totalCap"]}</td></tr><tr><td style="padding: 0 10px" colspan="100"><p style="line-height: 0.8">备注：收到货物请及时按单清点，如有疑问请在三个工作日与我公司联系逾期概不负责。</p><p style="line-height: 0.8">地址：四川省成都市双流区空港四路1537号六号库7号门&nbsp;&nbsp;电话:13547860288&nbsp;&nbsp;&nbsp;电话: 13547860388</p><p style="line-height: 0.8">发单人：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;录单人:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;客户签字:</p></td></tr>` : `<td>暂无数据</td>`}',
            tableHeaderRepeat: "page",
            tableFooterRepeat: "last",
            fontSize: 8,
            tableHeaderFontSize: 8,
            columns: [
              [
                {
                  width: 153.19082050145386,
                  title: "型材编码",
                  field: "profileCode",
                  checked: true,
                  columnId: "profileCode",
                  fixed: false,
                  rowspan: 1,
                  colspan: 1,
                  align: "center",
                  tableQRCodeLevel: 0,
                  tableSummaryTitle: true,
                  tableSummaryText: "test",
                  tableSummary: "",
                },
                {
                  width: 147.85994224131738,
                  title: "名称",
                  field: "profileName",
                  checked: true,
                  columnId: "profileName",
                  fixed: false,
                  rowspan: 1,
                  colspan: 1,
                  align: "center",
                  tableQRCodeLevel: 0,
                  tableSummaryTitle: true,
                  tableSummary: "",
                },
                {
                  width: 78.10543715311222,
                  title: "颜色",
                  field: "color",
                  checked: true,
                  columnId: "color",
                  fixed: false,
                  rowspan: 1,
                  colspan: 1,
                  align: "center",
                  tableQRCodeLevel: 0,
                  tableSummaryTitle: true,
                  tableSummary: "",
                },
                {
                  width: 84.10583754364245,
                  title: "单位",
                  field: "materialType",
                  checked: true,
                  columnId: "materialType",
                  fixed: false,
                  rowspan: 1,
                  colspan: 1,
                  align: "center",
                },
                {
                  width: 105.23796256047405,
                  title: "数量",
                  field: "quantity",
                  checked: true,
                  columnId: "quantity",
                  fixed: false,
                  rowspan: 1,
                  colspan: 1,
                  align: "center",
                },
              ],
            ],
          },
          printElementType: {
            title: "表格",
            type: "table",
            editable: true,
            columnDisplayEditable: true,
            columnDisplayIndexEditable: true,
            columnTitleEditable: true,
            columnResizable: true,
            columnAlignEditable: true,
            isEnableEditField: true,
            isEnableContextMenu: true,
            isEnableInsertRow: true,
            isEnableDeleteRow: true,
            isEnableInsertColumn: true,
            isEnableDeleteColumn: true,
            isEnableMergeCell: true,
          },
        },
      ],
      paperNumberLeft: 567.5,
      paperNumberTop: 20,
      paperNumberContinue: true,
      watermarkOptions: {
        content: "vue-plugin-hiprint",
        rotate: 25,
        timestamp: true,
        format: "YYYY-MM-DD HH:mm",
      },
    },
  ],
};
