export default {
  panels: [
    {
      index: 0,
      name: 1,
      height: 296.6,
      width: 210,
      paperHeader: 75,
      paperFooter: 778.9494949494949,
      printElements: [
        {
          options: {
            left: 175.5,
            top: 10.5,
            height: 27,
            width: 259,
            title: "销售结算单",
            fontSize: 19,
            fontWeight: "600",
            textAlign: "center",
            lineHeight: 26,
            coordinateSync: true,
            widthHeightSync: true,
            draggable: false,
            qrCodeLevel: 0,
          },
          printElementType: { title: "自定义文本", type: "text" },
        },
        {
          options: {
            left: 57.5,
            top: 12.5,
            height: 63,
            width: 115.5,
            src: "../printLogo.png",
            fit: "contain",
            right: 178.24635314941406,
            bottom: 84.75,
            vCenter: 120.49635314941406,
            hCenter: 53.25,
          },
          printElementType: { title: "图片", type: "image" },
        },
        {
          options: {
            left: 187.5,
            top: 97.5,
            height: 21,
            width: 232.5,
            title: "制单日期",
            field: "makeDate",
            testData: "2023年5月30日",
            coordinateSync: false,
            widthHeightSync: false,
            fontSize: 12,
            qrCodeLevel: 0,
            right: 387,
            bottom: 98.25,
            vCenter: 270.75,
            hCenter: 87.75,
          },
          printElementType: { title: "这是更新后的元素", type: "text" },
        },
        {
          options: {
            left: 407.5,
            top: 97.5,
            height: 9.75,
            width: 169.5,
            title: "单号",
            field: "orderNum",
            testData: "GR230530001",
            coordinateSync: false,
            widthHeightSync: false,
            fontSize: 12,
            qrCodeLevel: 0,
            right: 546.75,
            bottom: 89.25,
            vCenter: 462,
            hCenter: 84.375,
          },
          printElementType: { title: "这是更新后的元素", type: "text" },
        },
        {
          options: {
            left: 177,
            top: 113.5,
            height: 16,
            width: 120,
            field: "tel",
            testData: "18888888888",
            fontSize: 6.75,
            fontWeight: "700",
            textContentVerticalAlign: "middle",
            title: "电话",
            coordinateSync: false,
            widthHeightSync: false,
            qrCodeLevel: 0,
          },
          printElementType: { title: "客户电话", type: "text" },
        },
        {
          options: {
            left: 55.5,
            top: 113.5,
            height: 16,
            width: 120,
            field: "name",
            testData: "高级客户",
            fontSize: 6.75,
            fontWeight: "700",
            textContentVerticalAlign: "middle",
            title: "客户",
            coordinateSync: false,
            widthHeightSync: false,
            qrCodeLevel: 0,
            right: 177,
            bottom: 197.4999885559082,
            vCenter: 117,
            hCenter: 189.4999885559082,
          },
          printElementType: { title: "客户名称", type: "text" },
        },
        {
          options: {
            left: 460.5,
            top: 113.5,
            height: 16,
            width: 120,
            field: "writeDate",
            testData: "2020-01-01",
            fontSize: 6.75,
            fontWeight: "700",
            textContentVerticalAlign: "middle",
            title: "录单日期",
            coordinateSync: false,
            widthHeightSync: false,
            qrCodeLevel: 0,
          },
          printElementType: { title: "业务日期", type: "text" },
        },
        {
          options: {
            left: 17,
            top: 129,
            height: 93,
            width: 568.5,
            field: "table",
            tableBorder: "border",
            tableHeaderBorder: "topBorder",
            tableHeaderCellBorder: "border",
            tableBodyRowBorder: "topBorder",
            tableFooterBorder: "topBorder",
            fields: [
              { text: "型材编码", field: "profileCode" },
              { text: "名称", field: "profileName" },
              { text: "颜色", field: "color" },
              { text: "数量", field: "changeQuantity" },
              { text: "重量", field: "weight" },
              { text: "单价", field: "price" },
              { text: "金额", field: "totalPrice" },
              { text: "单位", field: "materialType" },
            ],
            right: 596.25,
            bottom: 240.49635314941406,
            vCenter: 312,
            hCenter: 193.99635314941406,
            coordinateSync: false,
            widthHeightSync: false,
            footerFormatter:
              'function(t,e,n,i){return n ? `<tr><td style="padding:0 10px">其他费用：</td><td style="padding:0 10px" colspan="100"></td></tr><tr><td style="padding:0 10px">合计：</td><td style="padding:0 10px">支数：${n.zhi}</td><td style="padding:0 10px">件数：${n["ge"]}</td><td style="padding:0 10px" colspan="3">重量：${n["totalWeight"]}</td><td style="padding:0 10px" colspan="2">金额：${n["totalPrice"]}</td></tr><tr><td>合计(大写)</td><td style="padding:0 10px" colspan="100">${n["totalCap"]}</td></tr>` : `<td>暂无数据</td>`}',
            tableHeaderRepeat: "page",
            tableFooterRepeat: "last",
            columns: [
              [
                {
                  width: 91.18359077849722,
                  title: "型材编码",
                  field: "profileCode",
                  checked: true,
                  columnId: "profileCode",
                  fixed: false,
                  rowspan: 1,
                  colspan: 1,
                  tableQRCodeLevel: 0,
                  tableSummaryTitle: true,
                  tableSummaryText: "test",
                  tableSummary: "",
                },
                {
                  width: 72.51520425675808,
                  title: "名称",
                  field: "profileName",
                  checked: true,
                  columnId: "profileName",
                  fixed: false,
                  rowspan: 1,
                  colspan: 1,
                  align: "center",
                  tableQRCodeLevel: 0,
                  tableSummaryTitle: true,
                  tableSummary: "",
                },
                {
                  width: 59.32567469154068,
                  title: "颜色",
                  field: "color",
                  checked: true,
                  columnId: "color",
                  fixed: false,
                  rowspan: 1,
                  colspan: 1,
                  align: "center",
                  tableQRCodeLevel: 0,
                  tableSummaryTitle: true,
                  tableSummary: "",
                },
                {
                  width: 44.16320295241024,
                  title: "单位",
                  field: "materialType",
                  checked: true,
                  columnId: "materialType",
                  fixed: false,
                  rowspan: 1,
                  colspan: 1,
                },
                {
                  width: 71.19990947414936,
                  title: "数量",
                  field: "quantity",
                  checked: true,
                  columnId: "quantity",
                  fixed: false,
                  rowspan: 1,
                  colspan: 1,
                },
                {
                  width: 71.4044453931504,
                  title: "重量",
                  field: "weight",
                  checked: true,
                  columnId: "weight",
                  fixed: false,
                  rowspan: 1,
                  colspan: 1,
                },
                {
                  width: 72.74097556034135,
                  title: "单价",
                  field: "price",
                  checked: true,
                  columnId: "price",
                  fixed: false,
                  rowspan: 1,
                  colspan: 1,
                },
                {
                  width: 85.96699689315265,
                  title: "金额",
                  field: "totalPrice",
                  checked: true,
                  columnId: "totalPrice",
                  fixed: false,
                  rowspan: 1,
                  colspan: 1,
                  tableQRCodeLevel: 0,
                  tableSummaryTitle: true,
                  tableSummaryText: "test",
                  tableSummary: "",
                  tableSummaryAlign: "left",
                },
                {
                  width: 83.80566801619433,
                  checked: false,
                  fixed: false,
                  rowspan: 1,
                  colspan: 1,
                },
                {
                  width: 83.80566801619433,
                  checked: false,
                  fixed: false,
                  rowspan: 1,
                  colspan: 1,
                },
              ],
            ],
          },
          printElementType: {
            title: "表格",
            type: "table",
            editable: true,
            columnDisplayEditable: true,
            columnDisplayIndexEditable: true,
            columnTitleEditable: true,
            columnResizable: true,
            columnAlignEditable: true,
            isEnableEditField: true,
            isEnableContextMenu: true,
            isEnableInsertRow: true,
            isEnableDeleteRow: true,
            isEnableInsertColumn: true,
            isEnableDeleteColumn: true,
            isEnableMergeCell: true,
          },
        },
        {
          options: {
            left: 67.5,
            top: 786,
            height: 9.75,
            width: 472.5,
            title:
              "备注：收到货物请及时按单清点，如有疑问请在三个工作日与我公司联系逾期概不负责。",
            coordinateSync: false,
            widthHeightSync: false,
            fontSize: 6,
            qrCodeLevel: 0,
            right: 540,
            bottom: 797.9999885559082,
            vCenter: 303.75,
            hCenter: 793.1249885559082,
          },
          printElementType: { title: "文本", type: "text" },
        },
        {
          options: {
            left: 67.5,
            top: 802.5,
            height: 9.75,
            width: 226.5,
            title: "地址：四川省成都市双流区空港四路1537号六号门4号门",
            coordinateSync: false,
            widthHeightSync: false,
            fontSize: 6,
            qrCodeLevel: 0,
            right: 291.75,
            bottom: 808.5,
            vCenter: 178.5,
            hCenter: 803.625,
          },
          printElementType: { title: "文本", type: "text" },
        },
        {
          options: {
            left: 457.5,
            top: 802.5,
            height: 9.75,
            width: 81,
            title: "电话: 13547860388",
            coordinateSync: false,
            widthHeightSync: false,
            fontSize: 6,
            qrCodeLevel: 0,
            right: 534,
            bottom: 813.7499828338623,
            vCenter: 493.5,
            hCenter: 808.8749828338623,
          },
          printElementType: { title: "文本", type: "text" },
        },
        {
          options: {
            left: 336,
            top: 802.5,
            height: 9.75,
            width: 81,
            title: "电话: 13547860288",
            coordinateSync: false,
            widthHeightSync: false,
            fontSize: 6,
            qrCodeLevel: 0,
            right: 417,
            bottom: 812.2499828338623,
            vCenter: 376.5,
            hCenter: 807.3749828338623,
          },
          printElementType: { title: "文本", type: "text" },
        },
        {
          options: {
            left: 220.5,
            top: 822,
            height: 9.75,
            width: 106.5,
            title: "录单人: ",
            coordinateSync: false,
            widthHeightSync: false,
            fontSize: 6,
            qrCodeLevel: 0,
            right: 326.25,
            bottom: 831.7499828338623,
            vCenter: 273,
            hCenter: 826.8749828338623,
          },
          printElementType: { title: "文本", type: "text" },
        },
        {
          options: {
            left: 372,
            top: 822,
            height: 9.75,
            width: 106.5,
            title: "客户签字: ",
            coordinateSync: false,
            widthHeightSync: false,
            fontSize: 6,
            qrCodeLevel: 0,
            right: 473.25,
            bottom: 834.7500114440918,
            vCenter: 420,
            hCenter: 829.8750114440918,
          },
          printElementType: { title: "文本", type: "text" },
        },
        {
          options: {
            left: 67.5,
            top: 822,
            height: 9.75,
            width: 106.5,
            title: "发单人: ",
            coordinateSync: false,
            widthHeightSync: false,
            fontSize: 6,
            qrCodeLevel: 0,
            right: 175.5,
            bottom: 832.4999828338623,
            vCenter: 122.25,
            hCenter: 827.6249828338623,
          },
          printElementType: { title: "文本", type: "text" },
        },
      ],
      paperNumberLeft: 567.5,
      paperNumberTop: 20,
      watermarkOptions: {
        content: "vue-plugin-hiprint",
        rotate: 25,
        timestamp: true,
        format: "YYYY-MM-DD HH:mm",
      },
    },
  ],
};
